<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?=$title?></title>
	<style type="text/css">
		html, body {
			margin: 0;
			padding: 0;
			font-family: verdana;
		}
		div.header {
			z-index: 2;
			position: fixed;
			width: 100%;
			height: 129px;
			box-shadow: 0px 3px 20px #444;
		}
		div.header div.title {
			text-align: center;
			font-family: arial black;
			padding: 10px;
			background-color: #ddd;
			height: 70px;
			font-size: 50px;
			letter-spacing: 4px;
			text-shadow: 2px 2px 4px #888;
			font-weight: bolder;
		}

		div.header div.menu {
			background-color: #5f5f5f;
			height: 39px;
		}

		div.header div.menu ul {
			display: block;
			height: 39px;
			padding: 0;
			margin: 0;
		}

		div.header div.menu li {
			display: block;
			float: left;
			padding: 10px;
			margin-right: 10px;
			transition: background-color 0.5s;
		}
		div.header div.menu li a {
			color: #fff;
			text-decoration: none;
			text-transform: uppercase;
		}

		div.header div.menu li:hover {
			color: #fff;
			text-decoration: none;
			background-color: #222;
			transition: background-color 0.5s;
		}

		div.content {
			z-index: 1;
			position: relative;
			width: 80%;
			margin-left: 10%;
			margin-right: 10%;
			float: left;
			margin-top: 129px;
			color: #000;
		}

		div.content h1 {
			color: #333;
		}

		div.content p {
			color: #555;
		}

		table.info {
			width: 100%;
		}

		table.info tr.header {
			background-color: #666;
			text-align: center;
		}

		table.info tr.header td {
			font-weight: bolder;
			letter-spacing: 2px;
		}

		table.info tr td:first-child {
			text-align: center;
		}

		table.info tr:not(.header) td {
			color: #444;
			padding-left: 10px;
			padding-right: 10px;
		}

		table.info tr.header :first-child {
			width: 30%;
		}
		table.info tr {
			background-color: #ddd;
		}

		table.info span.positive {
			color: #0a0;
		}

		table.info span.negative {
			color: #a00;	
		}


	</style>
</head>
<body>
	<div class="header">
		<div class="title"><?=$packageName?></div>
		<div class="menu">
			<ul>
				<?php 
				$tabs = 4;
				$firstLine = true;
				foreach ($menu as $title => $link) {
					if ($firstLine) {
						echo "<li><a href='$link'>$title</a></li>\n";
						$firstLine = false;
					} else {
						echo str_repeat("\t", $tabs),"<li><a href='$link'>$title</a></li>\n";
					}	
				}
				?>
			</ul>
		</div>
	</div>
	<div class="content">
		<?=$yield?>
	</div>
</body>
</html>
