<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?=$title?></title>
	<link rel="stylesheet" type="text/css" href="/css/layout.css">
</head>
<body>
	<div class="header">
		<div class="title">
			<h1><?=$packageName?></h1>
			<p><?=$description?></p>
		</div>
		<div class="menu">
			<ul>
				<?php 
				$tabs = 4;
				$firstLine = true;
				foreach ($menu as $title => $link) {
					if ($firstLine) {
						echo "<li><a href='$link'>$title</a></li>\n";
						$firstLine = false;
					} else {
						echo str_repeat("\t", $tabs),"<li><a href='$link'>$title</a></li>\n";
					}	
				}
				?>
			</ul>
		</div>
	</div>
	<div class="content">
		<?=$yield?>
	</div>
</body>
</html>
